# Generated by Django 5.0 on 2023-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateField(),
        ),
    ]
