# Generated by Django 5.0 on 2023-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_notes_uploadingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to='note'),
        ),
    ]
