# Generated by Django 5.0 on 2023-12-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_notes_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(choices=[('pdf', 'PDF'), ('doc', 'DOC/DOCX'), ('CIVIL', 'CIVIL'), ('ppt', 'PPT/WORD'), ('zip', 'ZIP'), ('image', 'IMAGE'), ('OTHER', 'OTHER')], default='pdf', null=True, upload_to='note'),
        ),
    ]
