# Generated by Django 5.0 on 2023-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_alter_notes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
